server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

services:
  notification-url: http://NOTIFICATION-SERVICE/notification


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

auth:
  verification-code:
    validity-duration: 300 # 5 minutes
    length: 4
    resend-duration: 60 # 1 minute
    request-limit: 3

